# Generated by Django 2.1.1 on 2019-09-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modeified_date',
            new_name='modified_date',
        ),
    ]
